FLAMEGPU/FLAMEGPU

examples/Sugarscape/src/model/XMLModelFile.xml
This fixes the visualisation for the included example, and likely also behaviour.
The simpler of 2 solutions for #22.
The alternative of fixing the issue to allow a dynamic population sizes at run time up to the maximum at compile time would be non-trivial.
=> Reduce maximum sugarscape agent population to match 0.xml

FLAMEGPU/templates/main.xslt
When using `printf` anywhere in the `singleIteration()` function the lack of `\n` after 'Processing Simulation Step' results in line mangling, unless the first print begins with a newline.
`printf('Done')` is not really required, either the next iteration will begin and print a new line or the total processing time will be output, so `Done` doesn't add much.
This is relatively subjective, so feel free to reject this if you disagree @mondus.
=> Modify printf statements for each iteration

tools/model2dot.py
Added 'Layer' notation on one side to force ranking.
The solution will solve John Charleton's model. This is a partial fix. 
See also issue #46 (in progress)
=> added rank notation to the diagram

.gitignore, examples/Analytics/Analytics.vcxproj, examples/Analytics/Makefile, examples/Boids_BruteForce/Boids_BruteForce.vcxproj, examples/Boids_BruteForce/Makefile, examples/Boids_Partitioning/Boids_Partitioning.vcxproj, examples/Boids_Partitioning/Makefile, examples/CirclesBruteForce_double/CirclesBruteForce_double.vcxproj, examples/CirclesBruteForce_double/Makefile, examples/CirclesBruteForce_float/CirclesBruteForce_float.vcxproj, examples/CirclesBruteForce_float/Makefile, examples/CirclesPartitioning_double/CirclesPartitioning_double.vcxproj, examples/CirclesPartitioning_double/Makefile, examples/CirclesPartitioning_float/CirclesPartitioning_float.vcxproj, examples/CirclesPartitioning_float/Makefile, examples/GameOfLife/GameOfLife.vcxproj, examples/GameOfLife/Makefile, examples/Keratinocyte/Keratinocyte.vcxproj, examples/Keratinocyte/Makefile, examples/PedestrianLOD/Makefile, examples/PedestrianLOD/PedestrianLOD.vcxproj, examples/PedestrianNavigation/Makefile, examples/PedestrianNavigation/PedestrianNavigation.vcxproj, examples/StableMarriage/Makefile, examples/StableMarriage/StableMarriage.vcxproj, examples/Sugarscape/Makefile, examples/Sugarscape/Sugarscape.vcxproj, examples/Template/Makefile, examples/Template/Template.vcxproj
Also removes SM_20 from the default build architectures, and adds SM_60
Closes #67 
Achieved using `sed`
```
find ./examples -type f -name "*.vcxproj" -exec sed -i 's/ToolsVersion="12.0"/ToolsVersion="14.0"/g' {} +
find ./examples -type f -name "*.vcxproj" -exec sed -i 's/<PlatformToolset>v120<\/PlatformToolset>/<PlatformToolset>v140<\/PlatformToolset>/g' {} +
find ./examples -type f -name "*.vcxproj" -exec sed -i 's/CUDA 7.0./CUDA 8.0./g' {} +
find ./examples -type f -name "*.vcxproj" -exec sed -i 's/compute_20,sm_20;compute_30,sm_30;compute_35,sm_35;compute_50,sm_50/compute_30,sm_30;compute_35,sm_35;compute_50,sm_50;compute_60,sm_60/g' {} +
find ./examples -type f -name "Makefile" -exec sed -i 's/cuda-7.5/cuda-8.0/g' {} +
find ./examples -type f -name "Makefile" -exec sed -i 's/20 30 35 …
```
=> Update examples to use VS2015 (windows) and CUDA 8.0

FLAMEGPU/templates/header.xslt, FLAMEGPU/templates/simulation.xslt, bin/x64/HostAgentCreation.bat, examples/HostAgentCreation/HostAgentCreation.sln, examples/HostAgentCreation/HostAgentCreation.vcxproj, examples/HostAgentCreation/HostAgentCreation.vcxproj.filters, examples/HostAgentCreation/Makefile, examples/HostAgentCreation/iterations/0.xml, examples/HostAgentCreation/src/model/XMLModelFile.xml, examples/HostAgentCreation/src/model/functions.c
Allows users to specify the creation of agents on the host, and transfer
to target states on the device.
Utility functions are provided to allocate and deallocate agent structures and arrays of structures, including support for agent variable arrays.
An associated example is included, demonstrating use of the additional functionality.
Additionally, a new `#define` is created for the length of agent variable arrays.
Closes #73
=> Add Host based agent creation and associated example.

FLAMEGPU/templates/visualisation.xslt, examples/Boids_Partitioning/src/visualisation/visualisation.h
+ Pausing of simulation
+ `space` to pause the simulation
+ `->` (right arrow) to step a single iteration
+ `#define PAUSE_ON_START` in `visualisation.h` to pause before the first iteration.
+  Window Reshaping
+ uses `glutReshapeFunc` to enable reshaping of the window without content distortion!
For now I have omitted the "Y is up" option, as it's not necessary and if anyone is going down that route they will probably have a custom visualisation anyway.
=> Rc1.5/visualisation pause

FLAMEGPU/templates/header.xslt
Resolves #121 
This allows users to use `#if defined()` to write a `functions.c` file which is portable between message partitioning techniques. I.e. It is possible to modify `XMLModelFile.xml` to use an alternative partitioning teqchnique, and not have to modify `functions.c`. 
This is very useful for benchmarking partitioning methods, and much cleaner than duplicating the project.
=> Add macro definition for a message partitioning type

FLAMEGPU/templates/functions.xslt
suggests correct function prototypes in functions.xslt for spatially partitioned and discrete partitioned messages - i.e `agent_x`, `agent_y`, `agent_z`, and passes the PBM for spatial messages.
Closes #119
=> Update functions.xslt message list parsing for partitioned messaging

FLAMEGPU/templates/io.xslt
Fixes segfault on linux when directory passed as input argument. 
This had to use `#ifdef` and a linux specific fix as cross platform disk IO is not good.
Closes #118
=> Rc1.5/linux segfault fix

FLAMEGPU/templates/io.xslt, FLAMEGPU/templates/simulation.xslt
Fixes the issues of crashses / segfaults for empty initial states files.
+ Raises a warning if the file is completely empty (0 bytes read)
+ Adds a check for `discrete` agent population sizes
+ Avoids an `invalid launch configuration` issue when an discrete agent state has `0` population. This check was previously only applied to `continuous` agents.
+ This is likely better than not allowing simulations with empty statelists to execute, as agents may be created from `step` functions in `1.5`.
Closes #148
=> Rc1.5/empty xml fix

tools/common.mk
This allows different SMS to be used for different cuda versions
A step towards full CUDA 9 support (#136)
=> Add NVCC version detection to make files

FLAMEGPU/templates/io.xslt
Closes #153
Tested by locking output file `1.xml` with MS Word.
Correctly produces an error message and exits.
=> Check that output XML file has been opened for writing successfully

FLAMEGPU/templates/main.xslt
Logs GPU device id, name, Compute Capability, Driver Mode and PCI Bus ID to stdout.
I.e. 
```
GPU 0: TITAN X (Pascal), SM61, WDDM, pciBusId 2
```
Closes #152
=> Add logging of GPU info to stdout

FLAMEGPU/templates/io.xslt, FLAMEGPU/templates/main.xslt
Closes #84.
+ Usage instructions updated to reflect recent changes
+ `inputpath` is now set to `""` and not used if it does not exist.
+ Variables are initialised correctly even if no input file specified
+ `outputpath` is either:
+ Passed in from command line if `inputpath` is a directory
+ Parent of `inputpath` if `inputpath` is a file (which does or does not exist)
+ The current working directory if the parent of `inputpath` does not exist.
=> Rc1.5/no init

FLAMEGPU/templates/main.xslt
Re-adds the `getOutputDir` functions I accidentally removed whilst working on `main.xslt`
=> Add missing getOutputDir function

examples/Analytics/Makefile, examples/Boids_BruteForce/Makefile, examples/Boids_Partitioning/Makefile, examples/Boids_PartitioningVecTypes/Makefile, examples/CirclesBruteForce_double/Makefile, examples/CirclesBruteForce_float/Makefile, examples/CirclesPartitioning_double/Makefile, examples/CirclesPartitioning_float/Makefile, examples/EmptyExample/Makefile, examples/GameOfLife/Makefile, examples/HostAgentCreation/Makefile, examples/Keratinocyte/Makefile, examples/MonteCarlo_BATCH/Makefile, examples/MonteCarlo_MSMPR/Makefile, examples/PedestrianLOD/Makefile, examples/PedestrianNavigation/Makefile, examples/StableMarriage/Makefile, examples/Sugarscape/Makefile, tools/common.mk
Closes #166
Supported by uncommenting the following lines(s) as required.
```
```
=> Disable XSLT transform from individual Makefiles

examples/Makefile
Can now run 'make' from within 'examples' without seeing warnings re this.
=> Remove MonteCarlo projects from Makefile as no corresponding dirs exist.

examples/Analytics/Makefile, examples/Boids_BruteForce/Makefile, examples/Boids_Partitioning/Makefile, examples/Boids_PartitioningVecTypes/Makefile, examples/CirclesBruteForce_double/Makefile, examples/CirclesBruteForce_float/Makefile, examples/CirclesPartitioning_double/Makefile, examples/CirclesPartitioning_float/Makefile, examples/EmptyExample/Makefile, examples/GameOfLife/Makefile, examples/HostAgentCreation/Makefile, examples/Keratinocyte/Makefile, examples/Makefile, examples/MonteCarlo_BATCH/Makefile, examples/MonteCarlo_MSMPR/Makefile, examples/PedestrianLOD/Makefile, examples/PedestrianNavigation/Makefile, examples/StableMarriage/Makefile, examples/Sugarscape/Makefile, tools/common.mk
If makefiles are changes, a rebuild is forced of all targets.
make help instructs the user that if variables are specified on the command line,
they should use -B on the first call with the new flags, to force a rebuild.
Closes #168
=> Update makefiles to suggest using -B and depend on MAKEFILE_LIST

tools/common.mk
Verbose output of the xsltproc / xmmlint command shows that it is actually occuring - which is useful.
=> Explicitly output xlstproc commands from make

examples/Analytics/Analytics.vcxproj, examples/Boids_BruteForce/Boids_BruteForce.vcxproj, examples/Boids_Partitioning/Boids_Partitioning.vcxproj, examples/Boids_PartitioningVecTypes/Boids_PartitioningVecTypes.vcxproj, examples/CirclesBruteForce_double/CirclesBruteForce_double.vcxproj, examples/CirclesBruteForce_float/CirclesBruteForce_float.vcxproj, examples/CirclesPartitioning_double/CirclesPartitioning_double.vcxproj, examples/CirclesPartitioning_float/CirclesPartitioning_float.vcxproj, examples/EmptyExample/EmptyExample.vcxproj, examples/GameOfLife/GameOfLife.vcxproj, examples/HostAgentCreation/HostAgentCreation.vcxproj, examples/Keratinocyte/Keratinocyte.vcxproj, examples/PedestrianLOD/PedestrianLOD.vcxproj, examples/PedestrianNavigation/PedestrianNavigation.vcxproj, examples/StableMarriage/StableMarriage.vcxproj, examples/Sugarscape/Sugarscape.vcxproj, tools/common.mk, tools/update_cuda_version_visual_studio.py
This now builds under linux with CUDA 9.0 and CUDA 9.1 with no additional warnings.
Prior to merging, the following must be done:
+ [x] Test under windows 
+ [x] Determine which CUDA version we intend to set as default for visual studio
+ [x] **Optional** Provide a script which will update the CUDA version used by all example projects. #170
=> CUDA 9.X support

FLAMEGPU/templates/header.xslt, FLAMEGPU/templates/simulation.xslt, examples/HostAgentCreation/src/model/XMLModelFile.xml, examples/HostAgentCreation/src/model/functions.c
Memcpy are handelled transparently by tracking if the host data has been updated or not
This includes resetting the flag if device data is modified by the host function.
Agent array variables and vector types are both supported
The HostAgentCreation examples has been updated to demonstrate this functionality using a custom output function.
i.e. a CSV file containing a subset of the agent's data is output per iteration in the step function.
Additionally, FLAME GPU keeps track of the iteration number (on the host only), which was required for transparent implementation of memcpy.
It will be worth noting in the documentation that it would be possible to severly hurt performance using these methods.
Closes #178
=> Implement agent variable access on the host

examples/Boids_BruteForce/src/model/functions.c, examples/Boids_Partitioning/src/model/functions.c, examples/Boids_PartitioningVecTypes/src/model/functions.c
The 3 implementations of the Boids models each contained 2 bugs relating to the calculation of the velocity matching (Alignment) rule, as highlighted in #62 .
I've confirmed that they were incorrect (`collision_velocity` always `{0.0f,0.0f,0.0f}`) and implemented the fix as suggested by @nikic.
I've also renamed some variables and modified some comments to add clarity, that the values are perceived values rather than global values (as they are within the interaction radius of the agent).
=> Rc1.5/boids rule2 fix

FLAMEGPU/templates/simulation.xslt
Under certain conditions agent will not need to run append function, and can simply pointer swap. Provides better performance for large agent data types.
Not tested for all use cases.
@mozhgan-kch 
See #65
=> Append agent condition

tools/common.mk
Naming the file functions.c resulted in the compiler attempting to use the dynamic file inplace of the model file.
This is unwanted behaviour, so the output file of the outline has been renamed as a simple fix
=> Rename destination file of generated functions.c outline

FLAMEGPU/templates/header.xslt, FLAMEGPU/templates/simulation.xslt, examples/Analytics/src/model/functions.c
Implemented using thrust, so not the most efficient if used regurally.
A CUB implementation would be more performant but time consuming to implement.
Not available for vector types, or array agent variables
Closes #213
=> Add min and max agent variable analytics functions.

FLAMEGPU/templates/functions.xslt, FLAMEGPU/templates/simulation.xslt
+ Explicitly error when:
+ `continuous` agents have function(s) which output `discretePartitioned` messages
+ `discrete` agents have functions(s) which output `not(discretePartitioned)` messages 
+ Add appropriate templating `<CONTINUOUS>` or `<DISCRETE_2D>` to `functions.xslt` template for `get_first_*`, `get_next_*` and `add_*` discrete message functions.
Closes #216
=> Rc1.5/discrete agent brute force messages

FLAMEGPU/templates/header.xslt
Closes #211 
This is not a necessity but could be useful. It **is** something we need to consider for FLAME GPU 2
=> Add FLAME GPU version macros following Semantic Versioning

FLAMEGPU/templates/io.xslt, examples/Analytics/Makefile, examples/Boids_BruteForce/Makefile, examples/Boids_Partitioning/Makefile, examples/Boids_PartitioningVecTypes/Makefile, examples/CirclesBruteForce_double/Makefile, examples/CirclesBruteForce_float/Makefile, examples/CirclesPartitioning_double/Makefile, examples/CirclesPartitioning_float/Makefile, examples/EmptyExample/Makefile, examples/GameOfLife/Makefile, examples/HostAgentCreation/Makefile, examples/Keratinocyte/Makefile, examples/MonteCarlo_BATCH/Makefile, examples/MonteCarlo_MSMPR/Makefile, examples/PedestrianLOD/Makefile, examples/PedestrianNavigation/Makefile, examples/RestrictedFlowGraph/Makefile, examples/StableMarriage/Makefile, examples/Sugarscape/Makefile, tools/common.mk
Downgrade array element mismatch error to a warning. I.e if enough memory is allocated for 12 integers, but only 1 is provided, elements 1 to 11 will be set to the default value (rather than having to specify all values). 
Can be suppressed by defining SUPPRESS_VARIABLE_ARRAY_ELEMENT_WARNING
=> Downgrade array element mismatch error to a warning

FLAMEGPU/templates/FLAMEGPU_kernals.xslt, FLAMEGPU/templates/_common_templates.xslt, FLAMEGPU/templates/header.xslt, FLAMEGPU/templates/io.xslt, FLAMEGPU/templates/simulation.xslt, examples/HostAgentCreation/src/model/XMLModelFile.xml, examples/HostAgentCreation/src/model/functions.c
Constrained to only work for agents with a variable 'id', of a singular integer type (short, int, long long) which may or may not be unsigned.
The maximum id from the initial states file is found and used as the first value available in an init function.
The current next id is maintained through host/device memcpys and state tracking to ensure that the correct value is available at the appropriate location.
i.e. for an agent named 'Agent' the function `generate_id_Agent()` can be called in a host or xagentOutput device function to generate a new identifier
Closes #247
Function / variable names can be changed if desired.
=> Implement ID Generation functions on the host and the device.

FLAMEGPU/templates/header.xslt, FLAMEGPU/templates/io.xslt, FLAMEGPU/templates/main.xslt
Some paths were limited to 100 chars, others to 1000. 
Now standardised to a preprocessor macro, with a value of `4096`, the maximum supported by the ext4 filesystem. NTFS / windows is currently limited to 260 by default, however this can be disabled through a registry edit on recent windows 10 builds.
=> Increase limit on path length(s) used by FLAME GPU

FLAMEGPU/templates/simulation.xslt
The linux xsltproc doesn't mind, even though XSLT 1.0 does not include scientific notation
=> Fix bug with windows XSLT processor not accepting scientific notation

readme.md
1. doi in ref enables easy access eg via Sci-Hub or Library Genesis as well as to publisher site.
2. Omitting www prefix should work but was giving 404 error no such site.
3. Both versions should presumably point to new site:
https://flamegpu.github.io/
If that is ready it should be fixed in its repo and/or DNS records.
=> Added doi, fixed broken link to old site.

examples/Boids_BruteForce/src/model/functions.c, examples/Boids_Partitioning/src/model/functions.c, examples/Boids_PartitioningVecTypes/src/model/functions.c
+ [x] Uses `glm::length` in place of existing `length` method from other boid examples
+ [x] replaces `__device__` with `__FLAME_GPU_FUNC__` to mask cuda from the modeller. 
As highlighted by @MILeach
=> Minor improvements to Boids Examples

FLAMEGPU/templates/_common_templates.xslt, FLAMEGPU/templates/header.xslt
Adjusts vector type support to allow vec in place of fvec, and glm prefixed variables in XMLModelFile.xml
i.e. `<type>` could previously be (for vectors of length `2`)
+ `ivec2`
+ `uvec2`
+ `fvec2`
+ `dvec2`
and now can also be:
+ `vec2`
+ `glm::vec2`
+ `glm::ivec2`
+ `glm::uvec2`
+ `glm::fvec2`
+ `glm::dvec2`
Where `vec2` maps to `fvec2`. (`vec2` is used in glm, while we introduced `fvec2` for concistency with the other types.)
This also applies to vectors of length `3` and `4`.
=> Expand supported vector types with additional aliases
