tools/model2dot.py
=> modifiled diagram Gen

FLAMEGPU/templates/FLAMEGPU_kernals.xslt, FLAMEGPU/templates/functions.xslt, FLAMEGPU/templates/header.xslt, FLAMEGPU/templates/io.xslt, FLAMEGPU/templates/main.xslt, FLAMEGPU/templates/simulation.xslt
=> Various minor fixes for typos etc in comments and printfs

FLAMEGPU/templates/simulation.xslt
Per-iteration and per-function (init/agent/step/exit functions) timing using cuda events, and also the population size for each agent state per iteration printed to `stdout`.
This instrumentation is enabled with a set of `#defines`. The value must be a positive non-zero integer (i.e. `1`) to be enabled.
```
#define INSTRUMENT_ITERATIONS 1
#define INSTRUMENT_AGENT_FUNCTIONS 1
#define INSTRUMENT_INIT_FUNCTIONS 1
#define INSTRUMENT_STEP_FUNCTIONS 1
#define INSTRUMENT_EXIT_FUNCTIONS 1
#define OUTPUT_POPULATION_PER_ITERATION 1
```
When enabled, the relevant measures are printed to `stdout`, which can then later be parsed  to produce graphs etc.
For instance, enabling all of the above flags on the `Analytics` example produces the following output:
```
Processing Simulation Step 1 …
```
=> Add Instrumentation for timing and population sizes

FLAMEGPU/templates/simulation.xslt
Closes #71 
Output lines include "Init" to identify from subsequent iterations.
=> Output agent population after init functions if instrumented

FLAMEGPU/templates/io.xslt, FLAMEGPU/templates/main.xslt, FLAMEGPU/templates/simulation.xslt, FLAMEGPU/templates/visualisation.xslt
Also uses EXIT_SUCCESS and EXIT_FAILURE for the return values for main()
Closes #40
=> Use EXIT_SUCCESS, EXIT_FAILURE or CUDA/GL error codes for all exit() calls

FLAMEGPU/templates/header.xslt, FLAMEGPU/templates/simulation.xslt
=> Disable analytics functions for agent variable arrays

FLAMEGPU/templates/functions.xslt
=> Remove unnecessary * characters from generated commented-out code

FLAMEGPU/templates/main.xslt, FLAMEGPU/templates/simulation.xslt, FLAMEGPU/templates/visualisation.xslt
=> Add missing newline characters from various error messages

FLAMEGPU/templates/header.xslt, FLAMEGPU/templates/simulation.xslt
=> Rc1.5/const getter arrays

FLAMEGPU/templates/simulation.xslt, examples/HostAgentCreation/src/model/XMLModelFile.xml
=> fixed in host agent generation

FLAMEGPU/templates/FLAMEGPU_kernals.xslt
Fixes bug with spatially partitioned messages and agent function conditons.
The combined effect of the PBM not being reset and the number of messages not being chekced when accessing the PBM resulted in old messages being accessed, when none should be available.
This resolves #120 .
=> Bugfix - Check spatially partiioned message count when loading messages.

examples/PedestrianNavigation/src/visualisation/GlobalsController.cpp, examples/PedestrianNavigation/src/visualisation/GlobalsController.h
=> Correct return types for getStateExit functions in PedestrianNav

FLAMEGPU/templates/FLAMEGPU_kernals.xslt
Match return type of several functions with return values.
Closes #137
=> Update return types / return values to match in several GPU functions

FLAMEGPU/templates/main.xslt
Implement runtime control of xml output.
`#define` of `OUTPUT_TO_XML` provides the default value, if console mode an additional optional argument after device index can be used to override this value.
I.e. 
`executable /path/to/0.xml <iterations> <gpu> <xml_output>
Closes #141
=> Rc1.5/output xml runtime

bin/linux-x64/Boids_BruteForce_console.sh, bin/linux-x64/Boids_BruteForce_visualisation.sh, bin/linux-x64/Boids_Partitioning_console.sh, bin/linux-x64/Boids_Partitioning_visualisation.sh, bin/linux-x64/CirclesBruteForce_double.sh, bin/linux-x64/CirclesBruteForce_float.sh, bin/linux-x64/CirclesPartitioning_double.sh, bin/linux-x64/CirclesPartitioning_float.sh, bin/linux-x64/EmptyExample_console.sh, bin/linux-x64/EmptyExample_visualisation.sh, bin/linux-x64/GameOfLife_console.sh, bin/linux-x64/GameOfLife_visualisation.sh, bin/linux-x64/HostAgentCreation.sh, bin/linux-x64/Keratinocyte_console.sh, bin/linux-x64/Keratinocyte_visualisation.sh, bin/linux-x64/MCBatch_console.sh, bin/linux-x64/MC_MSMPR_console.sh, bin/linux-x64/PedestrainLOD_console.sh, bin/linux-x64/PedestrainLOD_visualisation.sh, bin/linux-x64/PedestrainNavigation_console.sh, bin/linux-x64/PedestrainNavigation_visualisation.sh, bin/linux-x64/StableMarriage.sh, bin/linux-x64/Sugarscape_console.sh, bin/linux-x64/Sugarscape_visualisation.sh
=> Add linux bash scripts for launching examples

FLAMEGPU/templates/main.xslt
Adds runtime flags to get help usage from the command line.
=> Add -h and --help options to output usage

FLAMEGPU/templates/io.xslt
Also fixes a few bugs with outputting vector type agent variables.
Closes #159
=> Add environment constant output to iterations files

tools/update_cuda_version_visual_studio.py
=> Add script to automate updating cuda version in vxproj files

examples/Analytics/readme.md, examples/Boids_BruteForce/readme.md, examples/Boids_Partitioning/readme.md, examples/Boids_PartitioningVecTypes/readme.md, examples/CirclesBruteForce_double/readme.md, examples/CirclesBruteForce_float/readme.md, examples/CirclesPartitioning_double/readme.md, examples/CirclesPartitioning_float/readme.md, examples/EmptyExample/readme.md, examples/GameOfLife/readme.md, examples/HostAgentCreation/readme.md, examples/Keratinocyte/readme.md, examples/MonteCarlo_BATCH/readme.md, examples/MonteCarlo_MSMPR/readme.md, examples/PedestrianLOD/readme.md, examples/PedestrianNavigation/readme.md, examples/StableMarriage/readme.md, examples/Sugarscape/readme.md
Also updates / renames the MonteCarlo examples
Ref #87
=> Add simple descriptions of each example project.

FLAMEGPU/templates/FLAMEGPU_kernals.xslt
If the block/grid size generated is not an exact match to the population
or rather is larger than the maximum buffer size,
then out of bounds global reads/writes could occur for agent functions which iterate non-partitioned messaging.
This is prevented by thread bounds checking on global reads / writes, but as the agent function will still execute default values are loaded.
Agent array variables then presented possible issues, so null pointers are passed to the relevant functions which trigger special cases. This was the simplest change which does not require changing of function prototypes (and therfore functions.c).
Closes #189
=> Fix brute force partitioning out of bounds reads/writes

examples/Analytics/Analytics.vcxproj, examples/Boids_BruteForce/Boids_BruteForce.vcxproj, examples/Boids_Partitioning/Boids_Partitioning.vcxproj, examples/Boids_PartitioningVecTypes/Boids_PartitioningVecTypes.vcxproj, examples/CirclesBruteForce_double/CirclesBruteForce_double.vcxproj, examples/CirclesBruteForce_float/CirclesBruteForce_float.vcxproj, examples/CirclesPartitioning_double/CirclesPartitioning_double.vcxproj, examples/CirclesPartitioning_float/CirclesPartitioning_float.vcxproj, examples/EmptyExample/EmptyExample.vcxproj, examples/GameOfLife/GameOfLife.vcxproj, examples/HostAgentCreation/HostAgentCreation.vcxproj, examples/Keratinocyte/Keratinocyte.vcxproj, examples/PedestrianLOD/PedestrianLOD.vcxproj, examples/PedestrianNavigation/PedestrianNavigation.vcxproj, examples/StableMarriage/StableMarriage.vcxproj, examples/Sugarscape/Sugarscape.vcxproj
=> Update default CUDA version to cuda 9.2 in visual studio projects

FLAMEGPU/templates/simulation.xslt
=> Add compile time #error if discrete agents have conditional functions

FLAMEGPU/templates/main.xslt
=> Use XML output override parameter as frequency of XML output

FLAMEGPU/templates/io.xslt
=> Add support for comments in inital states file

FLAMEGPU/templates/header.xslt, FLAMEGPU/templates/main.xslt, FLAMEGPU/templates/simulation.xslt
Implements #240. Not sure if scoping and names are the best, but it works for console...
=> Early simulation exit

FLAMEGPU/templates/simulation.xslt
=> Fix placement of NVTX range markers for Init and Exit functions.
